SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE employees MODIFY empid INT AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS = 1;

ALTER TABLE employees MODIFY SSN VARCHAR(9) NOT NULL;

ALTER TABLE employees ADD UNIQUE (SSN);
